### ISSUE TITLE
500px API is now shut down?

### ISSUE THREAD

**Issue by dakkusingh** [500px/legacy-api-documentation#258]
Hi @mck182 am I right in understanding that 500px API is now shut down?

**Comment by mck182** [comment]
The history of 500px has always encouraged creative development, but as of January 24th 2018, 500px will no longer be offering free access to our API. This decision was made in order to protect our assets and improve our websites performance. Anyone with an existing key will continue to have access. If you are a potential partner and would like to discuss business opportunities or have questions regarding this matter please feel free to contact sales@500px.com.
-Martin, 500px
